# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

f1 <- function(x, y) {
    .Call(`_testTPS_f1`, x, y)
}

f2 <- function(x, y) {
    .Call(`_testTPS_f2`, x, y)
}

f3 <- function(x, y) {
    .Call(`_testTPS_f3`, x, y)
}

f4 <- function(x, y) {
    .Call(`_testTPS_f4`, x, y)
}

testfunction <- function(x, y) {
    .Call(`_testTPS_testfunction`, x, y)
}

meshgrid <- function(x, y, xv, yv) {
    invisible(.Call(`_testTPS_meshgrid`, x, y, xv, yv))
}

DistanceMatrix <- function(dsites, ctrs) {
    .Call(`_testTPS_DistanceMatrix`, dsites, ctrs)
}

radialFunction <- function(r, RBFtype, R, shape) {
    .Call(`_testTPS_radialFunction`, r, RBFtype, R, shape)
}

PLS <- function(dsites, ctrs, RBFtype, R, neval, alpha, shape) {
    .Call(`_testTPS_PLS`, dsites, ctrs, RBFtype, R, neval, alpha, shape)
}

testTps <- function(Epsilon, Eta, MinClusterSize, lambda) {
    invisible(.Call(`_testTPS_testTps`, Epsilon, Eta, MinClusterSize, lambda))
}

mpiinit <- function() {
    invisible(.Call(`_testTPS_mpiinit`))
}

mpifinalize <- function() {
    invisible(.Call(`_testTPS_mpifinalize`))
}

calculateTPS_hmat <- function(sites, values, M1, S, Epsilon, Eta, MinClusterSize, lambda) {
    .Call(`_testTPS_calculateTPS_hmat`, sites, values, M1, S, Epsilon, Eta, MinClusterSize, lambda)
}

calculateTPS_full <- function(values, full) {
    .Call(`_testTPS_calculateTPS_full`, values, full)
}

